### ISSUE TITLE
Java executable not found

### ISSUE THREAD

**Issue by Oladotunn** [sijomc/sonarscan-action#1]
Hi, 

Tried to run sonarqube scan in github actions, followed the usage instructions, but it gets stuck with this error
`Could not find 'java' executable in JAVA_HOME or PATH.`. Any idea what i'm not doing right please?

Here's the build link: https://github.com/Nautilus-Technologies/test/runs/1783199032?check_suite_focus=true

**Comment by sijomc** [comment]
@Oladotunn Please try without additional java environment variables. If that not works, share your workflow yml file and option which you created in GitHub secrets.

**Comment by Oladotunn** [comment]
Hey, @sijomc

 it works when i removed other java environment variables. However, got stuck elsewhere
`INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 22.525s
INFO: Final Memory: 15M/177M
ERROR: Error during SonarQube Scanner execution
INFO: ------------------------------------------------------------------------
org.sonar.java.AnalysisException: Your project contains .java files, please provide compiled classes with sonar.java.binaries property, or exclude them from the analysis with sonar.exclusions property.`

Here's how the workflow script looks like

`name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: SonarQube Scan
      uses: sijomc/sonarscan-action@1.1
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_LOGIN }}
        projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
        projectName: ${{ secrets.SONAR_PROJECT_KEY}}
`

**Comment by sijomc** [comment]
@Oladotunn Add `sonar-project.properties` file on the root directory and add `sonar.java.binaries=.`

**Comment by Oladotunn** [comment]
hey @sijomc, 

Thanks, this works just fine. Largely appreciated.
